In [1]:
import numpy as np

## Operações com arrays multidimensionais

### Lembre-se: a notação é sempre LINHA - COLUNA

In [2]:
A = [[1,2,3,4], [5,6,7,8], [10,20,30,40], [50,60,70,80]]

array = np.array(A)

print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [3]:
# Primeira linha
array[0]

array([1, 2, 3, 4])

In [4]:
array[2]

array([10, 20, 30, 40])

In [6]:
# Primeira linha e ultima coluna
array[0][-1]

4

In [7]:
# Atribuindo um valor a uma posição da matriz

array[0,0] = 0

array

array([[ 0,  2,  3,  4],
       [ 5,  6,  7,  8],
       [10, 20, 30, 40],
       [50, 60, 70, 80]])

### Trabalhando com intervalos

In [10]:
# Pegando os números centrais
array[1:3,1:3]

array([[ 6,  7],
       [20, 30]])

In [11]:
# Pegando o intervalo 7,8,30,40
array[1:3,2:4]

array([[ 7,  8],
       [30, 40]])

In [12]:
# Trazendo somente a última coluna
array[:,-1]

array([ 4,  8, 40, 80])

In [13]:
# Trazendo somente a última linha
array[-1,:]

array([50, 60, 70, 80])

In [ ]:
# Concatenando
A = np.array([[1,2],[3,4]])
B = np.array([[5,6]])

