In [1]:
import numpy as np

In [2]:
# A matriz só pode ser bidimensional

A = np.matrix([[1,2],[3,4]])

B = np.matrix([[5,3], [8,7]])

Z = np.array([
        [[2,6], [8,4]],
        [[2,6], [8,4]],
        [[2,6], [8,4]]
    ])

Y = np.array([2,6,8,4])

In [3]:
Z = np.matrix([
        [[2,6], [8,4]],
        [[2,6], [8,4]],
        [[2,6], [8,4]]
    ])

ValueError: matrix must be 2-dimensional

In [4]:
# Para saber a dimensão da matriz, conta-se os colchetes, neste caso temos uma matriz bidimensional
print(A)

[[1 2]
 [3 4]]


In [6]:
# Neste caso temos uma matriz tridimensional ou um cubo
print(Z)

[[[2 6]
  [8 4]]

 [[2 6]
  [8 4]]

 [[2 6]
  [8 4]]]


In [7]:
# Lê-se assim, uma matriz tridimensional com 2 linhas e 2 colunas
Z.shape

(3, 2, 2)

### Matriz inversa

In [8]:
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
from numpy.linalg import inv

In [10]:
print(inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Transposta

In [11]:
# Troca-se linha por coluna
print(A.T)

[[1 3]
 [2 4]]
