In [1]:
import numpy as np

### Tipagem de dados

In [2]:
# Podemos passar um tipo para o Array por parametro
a = np.array([-10, 10, 20, 30], dtype = 'float')

In [3]:
a

array([-10.,  10.,  20.,  30.])

In [4]:
# A propriedade dtype me retorna o tipo dos elementos do array
a.dtype

dtype('float64')

In [5]:
# Caso, eu, não passe o tipo para o python, ele definirá automaticamente
b = np.array([-10, 10, 20, 30])
b.dtype

dtype('int64')

In [6]:
# Caso exista um elemento diferente dos demais, o python irá tipar o array pelo elemento mais específico
c = np.array([10, 20, 30, 40.5])
c.dtype

dtype('float64')

In [7]:
# Poedmos também ter um tipo string
d = np.array(['Universidade', 'dos', 'dados'])
d.dtype

dtype('<U12')

In [8]:
# Array do tipo boleano
e = np.array([False, False, True])
e.dtype

dtype('bool')

### Cast de Arrays

In [10]:
f = np.array([-9, 10, 20.7])
f.dtype

dtype('float64')

In [11]:
# Posso realizar um CAST com a função astype()
f.astype(int)

array([-9, 10, 20])

### Criando Arrays com oprações artiméticas em tempo de execução

In [13]:
# Aprendemos que a função arange serve para criar um array
array = np.arange(0,5)
array

array([0, 1, 2, 3, 4])

In [14]:
# podemos criar uma array com qualquer operação aritimética
array = np.arange(0,10)*10
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
# Potencia
array = np.arange(10)**2
array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Operações aritiméticas entre arrays

In [18]:
a = np.arange(0,10)
b = np.arange(0,10)+1
print('Array A: ', a)
print('Array B: ', b)

Array A:  [0 1 2 3 4 5 6 7 8 9]
Array B:  [ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# Soma
a + b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [20]:
# Subtração
a - b

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [21]:
# Multiplicação
a * b

array([ 0,  2,  6, 12, 20, 30, 42, 56, 72, 90])

In [22]:
# Divisão
a / b

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ,
       0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ])

In [23]:
# Comparação de arrays
a == b

array([False, False, False, False, False, False, False, False, False,
       False])

In [24]:
a > b

array([False, False, False, False, False, False, False, False, False,
       False])

In [25]:
a < b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [26]:
# Podemos ainda utilizar a tabela verdade para comparar dois arrays, utilizando por exemplo a lógica AND
a1 = np.array([True, False, True, False])
b1 = np.array([False, False, True, False])
np.logical_and(a1, b1)

array([False, False,  True, False])

In [27]:
# OR
a1 = np.array([True, False, True, False])
b1 = np.array([False, False, True, False])
np.logical_or(a1, b1)

array([ True, False,  True, False])

### Arrays com tamanhos diferentes

In [28]:
x = np.array([1,2,3,4,5])
y = np.array([1,2,3])

In [29]:
x+y

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [30]:
x*y

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

### Dot Product

In [31]:
s = np.array([2,4,6])
w = np.array([2,2,2])

In [34]:
# Hadmard Product
s*w

array([ 4,  8, 12])

In [33]:
# Dot Product - soma dos produtos 4 + 8 + 12
print(np.dot(s,w))

24


In [35]:
r = np.array([3,7,10])
n = np.array([9,3,2])

In [37]:
# Hadmard Product
r*n

array([27, 21, 20])

In [38]:
print(np.dot(r,n))

68


### Cópias de arrays

In [39]:
# Neste caso não será um cópia, b receberá apenas a referencia de a
A = np.arange(10)

In [40]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
B = A[5:]

In [42]:
B

array([5, 6, 7, 8, 9])

In [43]:
A[:] = 0

In [44]:
B

array([0, 0, 0, 0, 0])

In [45]:
B

array([0, 0, 0, 0, 0])

In [46]:
A = np.arange(10)

In [47]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# Copiando
B = A[5:].copy()

In [49]:
B

array([5, 6, 7, 8, 9])

In [50]:
A[:] = 0

In [51]:
A

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
B

array([5, 6, 7, 8, 9])