# Numpy - Biblioteca matemática, mais utilizada aom álgebra linear, vetores e matrizes

In [1]:
import numpy as np

Estruturas unidimenssionais

In [3]:
a1 = np.array(['Spark', 'Hadoop', 'Python', 'R'])

In [5]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

# Arrays podem ter listas de tipos diferentes

Estruturas bidimensionais

In [6]:
a2 = np.array([['altura', 'largura', 'profundidade'], [42,78,10]])

In [7]:
a2

array([['altura', 'largura', 'profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [9]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
# tamano do array
print(a1.shape)
print(a2.shape)
print(a3.shape)
# (4,) 1 dimensão com 4 elementos
# (2,3) 2 dimensões com 3 elementos cada
# (3,3) 3 dimensões com 3 elementos cada

(4,)
(2, 3)
(3, 3)


In [16]:
# Dimensões do array
print('a1->',a1.ndim, ' dimensão')
print('a2->',a2.ndim, ' dimensões')
print('a3->',a3.ndim, ' dimensões')

a1-> 1  dimensão
a2-> 2  dimensões
a3-> 2  dimensões


Ausência ou presença de parênteses.

Podemos realizar uma analogia com características e ações. O uso de parênteses reflete uma ação, enquando a ausência, reflete uma característica.

In [17]:
# Ométodo max() não funciona em arrays de tipo heterogêneo
a3.max()

9

In [18]:
# Atributo
a2.ndim

2

# Método arrange

In [19]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
# Usando start/end - de 0 a 100 de 10 em 10
array = np.arange(0,100,10)

In [21]:
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# Criando estruturas de dados com linspace

In [23]:
# Fique atento: a diferença do linspace para o arange 
# é que o último argumento é o incremento, e no linspace 
# o último argumento é o número de elementos do 
# vetor(aleatório)
matriz = np.linspace(0,10,20)
matriz

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [25]:
matriz = np.linspace(0,10,5)
matriz

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [26]:
matriz = np.linspace(0,5,5)
matriz

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

# Estruturas de matrizes

In [27]:
matriz = np.zeros((10,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
matriz = np.ones((2,3))
matriz

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# Produz uma matriz do tipo identity
matriz = np.eye(10)
matriz

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
# Produz o mesmo resultado, porém podemos definir os numeros das diagonais
matriz = np.diag((2,4,6,8,10,12,14,16,18,20))
matriz

array([[ 2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  6,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 12,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 14,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 16,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 18,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 20]])

In [33]:
matriz = np.empty((3,3))
matriz

array([[1.67112369e-316, 1.67433946e-316, 6.94352223e-310],
       [6.94352222e-310, 6.94352103e-310, 6.94352105e-310],
       [6.94352225e-310, 6.94352105e-310, 3.95252517e-322]])

In [34]:
np.tile(np.array([[1,2],[3,4],[5,6]]),3) # Multiplica a matriz pela quantidade de números  que esta fora

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6]])

In [35]:
np.tile(np.array([[1,2],[3,4],[5,6]]), (3,6)) # Num de vezes do array na vertical, num de vezes do array na horizontal

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6],
       [1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4, 3, 4],
       [5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]])